%%
img=double(imread('../data/barbara.png'))/255;
img=imresize(img,1/2);
load('../pretrained/dict.mat');
filter{1}=reshape(dict',[5,5,1,4]);
load('../pretrained/dict16x25.mat');
filter{2}=reshape(dict',[5,5,4,4]);
load('a.mat');
%%
opt.maxiter=[100,100];
opt.filter{1}=a;
opt.filter{2}=filter{2};
opt.lambda=[1e-3,1e-3];
opt.L=[1e2,200];
opt.shape{1}=[2,2];
opt.shape{2}=[2,2];
[recx,v,p,s]=infer_inter_fista(img,opt,1);
psnr(img,recx)
opt.p{1}=p;
opt.s{1}=s;
imdisp(recx)
%%
[recx,v,p,s]=infer_inter_fista(img,opt,2);
imdisp(recx)