%
x=rand(50,50);
a=randn(5,5,1)/5;
[r,~,mv]=size(a);
v=zeros(size(x,1)+r-1,size(x,2)+r-1,mv);
for j=1:mv
    v(:,:,j)=conv2(rot90(a(:,:,j),2),x);
end
v=v+randn(size(v))*1;
b=randn(size(v));
d=randn(size(x));
tau=0;
eta=10;
%%
tic
[newdict]=bregman_update_dict_frcg(x,a,v,b,d,tau,eta,50);
toc
tic
[bdict,bL]=fmin_bench(x,a,v,b,d,tau,eta,2000);
toc
norm(newdict(:)-bdict(:),1)