%%
x=rand(50,50);
a=randn(5,5,2)/5;
[r,~,mv]=size(a);
v=zeros(size(x,1)+r-1,size(x,2)+r-1,mv);
for j=1:mv
    v(:,:,j)=conv2(rot90(a(:,:,j),2),x);
end
v=v+randn(size(v))*1;
b=randn(size(v));
d=randn(size(x));
tau=1;
eta=1;
L=50;

%%
x=double(imread('../data/barbara.png'))/255;
x=imresize(x,1/4);
a=randn(5,5,4);
[r,~,mv]=size(a);
v=zeros(size(x,1)+r-1,size(x,2)+r-1,mv);
v=inter_recv(x,a,v);
b=zeros(size(v));
d=zeros(size(x));
tau=1;
eta=1;
L=100;
%%
v=zeros(size(v));
b=zeros(size(b));
d=zeros(size(d));
[v,E]=bregman_update_coef_fista(x,a,v,b,d,tau,eta,100,50);
plot(E)
%%
v=zeros(size(v));
b=zeros(size(b));
d=zeros(size(d));
%%
tic
for k=1:100
v=bregman_update_coef_fista(x,a,v,b,d,tau,eta,L,5);
a=bregman_update_dict_frcg(x,a,v,b,d,tau,eta,20);
b=b+inter_recv(x,a,v)-v;
d=d+inter_recx(x,a,v)-x;
%norm(v(:),1)
%bregman_infeasibility_v(x,a,v)
bregman_infeasibility_x(x,a,v)
end
toc
