%%
x=rand(10,10);
a=randn(5,5,1)/5;
[r,~,mv]=size(a);
v=zeros(size(x,1)+r-1,size(x,2)+r-1,mv);
for j=1:mv
    v(:,:,j)=conv2(rot90(a(:,:,j),2),x);
end
v=v+randn(size(v))*1;
b=randn(size(v));
d=randn(size(x));
tau=1;
eta=1;
L=100;
%%
tic
[coef1]=bregman_update_coef_fista(x,a,v,b,d,tau,eta,10,200);
toc
E(end)
plot(E)
%%
[coef2,L]=fmin_bench_fista(x,a,v,b,d,tau,eta,50);
L
